### ISSUE TITLE
Kapanma

### ISSUE THREAD

**Issue by Muhteris** [Kyzaghan/Pokemon-Vortex-3-Ultimate-Bot#2]
Selam Kolay Gelsin Öncelikle Emeğiniz Ve Yardımlarınız  İçin Çok Teşekkür Etmek İsterim Bende Olan Problem Exp Bot Çalışırken Bi Zamandan Sonra 1 Saat Olur 2 Saat Olur Ya Pokemon Yenilemedi Tekrar Deniyor Hatasını Veriyor  Yada Kendi Kapanıyor.

**Comment by Kyzaghan** [comment]
Merhaba,
Yeni dosyalar ile deneyebilir misiniz?
