### ISSUE TITLE
A few bugs 

### ISSUE THREAD

**Issue by Rogerz0r** [Kyzaghan/Pokemon-Vortex-3-Ultimate-Bot#6]
-The older version of the bot dont catch some legendaries and when i change for night and cannot find none of them.

-nothing works except master ball the bot find but not capture and the new version dont capture none.
- the auto buy master ball is not working 
- i had 4 master ball and when i find one pokémon its say insufficient pokéballs.

-i've got 200 hyper potion but dont remeber to buy it its possible the bot is buying potions istead pokeballs.

[legendarys.txt](https://github.com/Kyzaghan/Pokemon-Vortex-3-Ultimate-Bot/files/431851/legendarys.txt)

**Comment by Kyzaghan** [comment]
Completed.
